[project]
name = "ghga_event_schemas"
version = "3.3.0"
description = "GHGA Event Schemas: A package that collects schemas used for events exchanged between GHGA service."
dependencies = [
    "jsonschema>=4.21.1,<5.0.0",
    "pydantic[email]>=2,<3",
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-event-schemas"
