[project]
name = "ghga_event_schemas"
version = "10.1.1"
description = "GHGA Event Schemas: A package that collects schemas used for events exchanged between GHGA service."
dependencies = [
    "jsonschema>=4.23.0,<5.0.0",
    "pydantic[email]>=2,<3",
    "pydantic_settings>=2,<3",
    "ghga-service-commons>=5.0.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/ghga-event-schemas"
